"""
FastAPI Book Recommendation Service

This module implements the data serving layer of the Book Recommendation
System. It exposes a REST API on top of the SQLite database generated by
the ETL pipeline.

The API allows clients to:
- Browse books with pagination
- Search books across multiple fields
- Fetch a book by ISBN
- Trigger the ETL pipeline in the background

This service is read-only with respect to data access and relies on
the pipeline to refresh the underlying database.
"""

import argparse
import os
import sys
import subprocess
import threading
import re
from typing import List, Optional
from pathlib import Path

from fastapi import FastAPI, Depends, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy import create_engine, Column, String, Text, or_
from sqlalchemy.orm import sessionmaker, declarative_base, Session
from pydantic import BaseModel, ConfigDict

# ======================================================
# DATABASE CONFIG
# ======================================================


# api/main.py
BASE_DIR = Path(__file__).resolve().parent.parent

DB_PATH = BASE_DIR / "data" / "storage_data" / "books.sqlite"

# IMPORTANT: make sure folder exists
DB_PATH.parent.mkdir(parents=True, exist_ok=True)

print("Using database at:", DB_PATH)   # DEBUG (temporary)

SQLALCHEMY_DATABASE_URL = f"sqlite:///{DB_PATH}"

engine = create_engine(
    SQLALCHEMY_DATABASE_URL,
    connect_args={"check_same_thread": False}
)

SessionLocal = sessionmaker(
    autocommit=False,
    autoflush=False,
    bind=engine
)

Base = declarative_base()

# ======================================================
# DATABASE MODEL (MATCHES SQLITE SCHEMA)
# ======================================================

class Book(Base):
    __tablename__ = "books"

    record_id = Column(String, primary_key=True, index=True)
    book_key = Column(String, unique=True, index=True)
    status = Column(String)

    accession_no = Column(String, nullable=True)
    class_no_book_no = Column(String, nullable=True)
    pages = Column(String, nullable=True)

    title = Column(String, index=True)
    authors = Column(String, nullable=True)
    isbn = Column(String, index=True, nullable=True)
    year = Column(String, nullable=True)

    subjects = Column(String, nullable=True)
    summary = Column(Text, nullable=True)
    publisher = Column(String, nullable=True)

# ======================================================
# DEPENDENCY
# ======================================================

def get_db():
    """
    Provide a database session per request.
    """
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

# ======================================================
# HELPERS
# ======================================================

def normalize_isbn(isbn: str) -> str:
    """
    Normalize ISBN by removing non-numeric characters.
    """
    return re.sub(r"[^0-9Xx]", "", isbn)

# ======================================================
# RESPONSE SCHEMAS
# ======================================================

class BookBase(BaseModel):
    record_id: str
    book_key: str
    status: str

    accession_no: Optional[str]
    class_no_book_no: Optional[str]
    pages: Optional[str]

    title: Optional[str]
    authors: Optional[str]
    isbn: Optional[str]
    year: Optional[str]

    subjects: Optional[str]
    summary: Optional[str]
    publisher: Optional[str]


class BookResponse(BookBase):
    model_config = ConfigDict(from_attributes=True)

# ======================================================
# FASTAPI APP
# ======================================================

app = FastAPI(
    title="Book Recommendation API",
    description="API for searching books enriched using Google Books",
    version="1.0.0"
)

# ======================================================
# CORS
# ======================================================

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ======================================================
# ROUTES
# ======================================================

@app.get("/books/", response_model=List[BookResponse])
def get_books(
    skip: int = 0,
    limit: int = 50,
    db: Session = Depends(get_db)
):
    """
    Fetch a paginated list of books.
    """
    return db.query(Book).offset(skip).limit(limit).all()


@app.get("/books/isbn/{isbn}", response_model=BookResponse)
def get_book_by_isbn(isbn: str, db: Session = Depends(get_db)):
    """
    Fetch a book by ISBN.
    """
    clean_isbn = normalize_isbn(isbn)
    book = db.query(Book).filter(Book.isbn == clean_isbn).first()

    if not book:
        raise HTTPException(status_code=404, detail="Book not found")

    return book

# ======================================================
# PIPELINE TRIGGER
# ======================================================

pipeline_lock = threading.Lock()

@app.post("/sync/")
def trigger_pipeline():
    """
    Trigger the ETL pipeline in the background.
    """
    def run_pipeline():
        if not pipeline_lock.acquire(blocking=False):
            return
        try:
            subprocess.run(
                [sys.executable, "../main.py"],
                cwd=os.getcwd()
            )
        finally:
            pipeline_lock.release()

    threading.Thread(target=run_pipeline, daemon=True).start()

    return {
        "status": "started",
        "message": "Pipeline triggered in background"
    }

# ======================================================
# CLI + ENTRY POINT
# ======================================================

def main():
    parser = argparse.ArgumentParser(
        description=
"""FASTAPI BOOK RECOMMENDATION SERVICE

PURPOSE
-------
Serve enriched book data via a REST API.

FEATURES
--------
- Paginated book listing
- ISBN-based lookup
- Full-text search across multiple fields
- Background pipeline trigger
- CORS-enabled for frontend use

DATABASE
--------
- SQLite database:
  data/storage_data/books.sqlite

ENDPOINTS
---------
GET  /books/
GET  /books/isbn/{isbn}
GET  /search/?q=...
POST /sync/

EXECUTION
---------
- Run via uvicorn for production
- Can also be launched directly for development
""",
        formatter_class=argparse.RawTextHelpFormatter
    )

    parser.parse_args()  # enables --help

    import uvicorn
    uvicorn.run(
        "main:app",
        host="127.0.0.1",
        port=8000,
        reload=True
    )

if __name__ == "__main__":
    main()
